"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-k%awlb#gsnaf_7r2^tbmlw7q=)i9k9)sii%h)08o8^u7t8b0_q",
)

DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "testserver",
    "django-shop-devops.onrender.com",
]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

    # Other packages
    "phonenumber_field",
    "rest_framework",
    "payments",

    # Custom apps
    "home",
    "users",
    "products",
    "orders",
    "support",
    "careers",
    "cart",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # allauth
    "allauth.account.middleware.AccountMiddleware",
]


# ============================================================
# URL / TEMPLATES / WSGI
# ============================================================

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates"
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                "products.context_processors.categories.categories_processor",
                "cart.context_processors.cart_summary",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"

# Thư mục chứa static gốc của project
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Thư mục Django sẽ gom toàn bộ static khi chạy collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# AUTHENTICATION
# ============================================================

AUTHENTICATION_BACKENDS = [
    # Django default authentication
    "django.contrib.auth.backends.ModelBackend",

    # allauth authentication
    "allauth.account.auth_backends.AuthenticationBackend",
]


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# CUSTOM USER MODEL
# ============================================================

AUTH_USER_MODEL = "users.CustomUser"


# ============================================================
# CART SETTINGS
# ============================================================

CART_MAX_ITEM_QTY = 50


# ============================================================
# DJANGO-ALLAUTH
# ============================================================

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": "ID",
            "secret": "SECRET",
            "key": "",
        }
    }
}


ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1

ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]

ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_LOGIN_METHODS = {"email"}

ACCOUNT_EMAIL_VERIFICATION = "mandatory"

ACCOUNT_CONFIRM_EMAIL_ON_GET = True

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = (
    "/?verification=1"
)

ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = (
    "/?verification=1"
)

LOGIN_REDIRECT_URL = "/"

ACCOUNT_LOGIN_ON_PASSWORD_RESET = True

ACCOUNT_FORMS = {
    "signup": "users.forms.CustomSignupForm",
}


# ============================================================
# PHONE NUMBER
# ============================================================

PHONENUMBER_DEFAULT_REGION = "IT"


# ============================================================
# EMAIL
# ============================================================

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# ============================================================
# DJANGO-PAYMENTS
# ============================================================

PAYMENT_MODEL = "orders.Payment"

PAYMENT_HOST = os.getenv(
    "PAYMENT_HOST",
    "127.0.0.1:8000",
)


# ============================================================
# STRIPE
# ============================================================

PAYMENT_VARIANTS = {
    "stripe": (
        "payments.stripe.StripeProviderV3",
        {
            "api_key": os.getenv(
                "STRIPE_API_KEY",
                "sk_test_123456",
            ),
            "use_token": True,

            # Nếu cần Stripe webhook khi deploy production:
            # "endpoint_secret": os.getenv(
            #     "STRIPE_ENDPOINT_SECRET",
            #     ""
            # ),

            "secure_endpoint": False,
        },
    )
}